services:
  fullnode:
    image: local/fullnode:1.16.0
    build:
      context: ../el/kamakazi-full-node
    container_name: fullnode
    hostname: fullnode
    restart: unless-stopped
    volumes:
      - nm1-data:/opt/el/data
    networks: [chain]
    ports:
      -"5000:8545"
      - "30304:30303/tcp"
      - "30304:30303/udp"

  archivenode:
    image: local/archivenode:1.16.0
    build:
      context: ../el/kamakazi-archive-node
    container_name: archivenode
    hostname: archivenode
    restart: unless-stopped
    volumes:
      - nm2-data:/opt/el/data
    networks: [chain]
    ports:
      -"5001:8545"

networks:
  chain:
    driver: bridge
    name: ${COMPOSE_PROJECT_NAME:-the-net}_chain

volumes:
  nm1-data:
  nm2-data:
